$schema: https://json-schema.org/draft-07/schema
additionalProperties: false
description: Settings for the application.
properties:
  $schema:
    anyOf:
    - type: string
    - type: 'null'
    default: null
    title: $Schema
  app_root_path:
    default: ''
    description: Prefix for the API path (e.g. "/api/v0")
    title: App Root Path
    type: string
  db_url:
    description: PostgreSQL database settings
    examples:
    - postgresql+asyncpg://postgres:postgres@localhost:5432/postgres
    - postgresql+asyncpg://postgres:postgres@db:5432/postgres
    format: password
    title: Db Url
    type: string
    writeOnly: true
  openai_api_key:
    description: 'Key to access the OpenAI API.'
    title: OpenAI Api Key
    type: string
    writeOnly: true

  cors_allow_origin_regex:
    default: .*
    description: 'Allowed origins for CORS: from which domains requests to the API are allowed. Specify as a regex: `https://.*.innohassle.ru`'
    title: Cors Allow Origin Regex
    type: string
required:
- db_url
- openai_api_key
title: Settings
type: object
