# yaml-language-server: $schema=settings.schema.yaml
$schema: "./settings.schema.yaml"
# ---------- Application settings ----- #
db_url: postgresql+asyncpg://postgres:postgres@localhost:5432/test-db
accounts:
  # Get from https://api.innohassle.ru/accounts/v0/tokens/generate-service-token?sub=byhack2025-local-dev&scopes=users&only_for_me=true
  api_jwt_token: "not-available"
api_key: "test-api-key"