"""changed character model

Revision ID: 7ea5c9793696
Revises: fad5e391abce
Create Date: 2025-09-13 22:53:47.306658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7ea5c9793696'
down_revision: Union[str, Sequence[str], None] = 'fad5e391abce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('title', sa.JSON(), nullable=False))
    op.add_column('characters', sa.Column('image', sqlmodel.AutoString(length=2048), nullable=True))
    op.add_column('characters', sa.Column('details', sa.JSON(), nullable=False))
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_column('characters', 'avatar_url')
    op.drop_column('characters', 'description')
    op.drop_column('characters', 'name')
    op.create_foreign_key(None, 'story_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story_sessions', type_='foreignkey') # type: ignore
    op.add_column('characters', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('avatar_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.drop_column('characters', 'details')
    op.drop_column('characters', 'image')
    op.drop_column('characters', 'title')
    # ### end Alembic commands ###
